version: '3.2'
services:
  jekyll:
    image: btquanto/docker-jekyll
    env_file: .environment
    ports:
      - 4000:4000
    volumes:
      - type: bind
        source: ./
        target: /src
        bind:
          propagate: shared
    command: jekyll serve -H 0.0.0.0 --draft
